services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - type: bind
        source: ./redis.conf
        target: /usr/local/etc/redis.conf
      - ./data/:/data/
    networks:
      - redis-network
    command: redis-server /usr/local/etc/redis.conf

networks:
  redis-network:
