services:
  redis:
    build: .
    container_name: redis
    volumes:
      - ./data/:/data/
    networks:
      - redis-network
    environment:
      - REDIS_PASSWORD=123456
      - DB_FILENAME=dump.rdb

networks:
  redis-network: