services:
  redis:
    image: redis-test
    container_name: redis
    volumes:
      # Put redis.conf in redis/
      - "/home/heddxh/redis/:/usr/local/etc/redis"
      - "/home/heddxh/redis/data/:/data"
    networks:
      - redis-network
    environment:
      - REDIS_PASSWORD = 123456

networks:
  redis-network:
